apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-microsweeper-quarkus
  name: microsweeper-dev-app-microsweeper-quarkus
  namespace: openshift-gitops
spec:
  destination:
    namespace: microsweeper-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/microsweeper-dev/apps/app-microsweeper-quarkus/overlays
    repoURL: https://github.com/jamesfalkner/microsweeper-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
