apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app-microsweeper-quarkus
  name: prod-app-microsweeper-quarkus
  namespace: openshift-gitops
spec:
  destination:
    namespace: prod
    server: https://api.theprod.rh-apps.org:6443
  project: default
  source:
    path: environments/prod/apps/app-microsweeper-quarkus/overlays
    repoURL: https://github.com/jamesfalkner/microsweeper-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
