apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: microsweeper-quarkus
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: microsweeper-quarkus
    app.kubernetes.io/name: microsweeper-quarkus
    app.kubernetes.io/part-of: microsweeper-quarkus
    app.openshift.io/runtime: quarkus
  name: microsweeper-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsweeper-quarkus
  template:
    metadata:
      labels:
        app: microsweeper-quarkus
    spec:
      containers:
      - name: microsweeper-quarkus
        imagePullPolicy: Always
        image: quay.io/jfalkner1/microsweeper-quarkus:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
